# bring up with: docker-compose up -d --build
version: '3.7'

services:
  reach:
    container_name: reach
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true